document.write( '  <div class=\"largescreen-header-container\">\n' );
document.write( '        <a href=\"index.html?category=all\"><img src=\"imgs/logo.png\" class=\"logo\" id=\"all\" /></a>\n' );
document.write( '        <nav class=\"main-nav\">\n' );
document.write( '            <a href=\"index.html?category=women\" class=\"navItem\">\n' );
document.write( '                <li id=\"women\">女裝</li>\n' );
document.write( '            </a>\n' );
document.write( '            <a href=\"index.html?category=men\" class=\"navItem\">\n' );
document.write( '                <li id=\"men\">男裝</li>\n' );
document.write( '            </a>\n' );
document.write( '            <a href=\"index.html?category=accessories\" class=\"navItem\">\n' );
document.write( '                <li id=\"accessories\">配件</li>\n' );
document.write( '            </a>\n' );
document.write( '        </nav>\n' );
document.write( '        <div class=\"right-nav forlargescreen\">\n' );
document.write( '            <a href=\"cart.html\"><img src=\"imgs/cart.png\" /></a>\n' );
document.write( '            <div class=\"cartCountNode\">0</div>\n' );
document.write( '            <input type=\"image\" img src=\"imgs/member.png\" class=\"fbMainLogin\" onclick=\"checkLoginState()\"/>\n' );
document.write( '        </div>\n' );
document.write( '    </div>\n' );
document.write( '\n' );
document.write( '    <div class=\"smallscreen-header-container\">\n' );
document.write( '        <div class=\"cart forsmallscreen\">\n' );
document.write( '            <a href=\"cart.html\"><img src=\"imgs/cart-mobile.png\" /></a>\n' );
document.write( '            <a href=\"cart.html\"><p>購物車</p></a>\n' );
document.write( '            <div class=\"cartCountNode\">0</div>\n' );
document.write( '        </div>\n' );
document.write( '        <div class=\"forsmallscreen\">|</div>\n' );
document.write( '        <div class=\"cart-member forsmallscreen\">\n' );
document.write( '            <a href=\"profile.html\"><input type=\"image\" img src=\" imgs/member-mobile.png\"/></a>\n' );
document.write( '            <p class="fbMainLogin" id=\"memberclick\" onclick=\"checkLoginState()\">會員</p>\n' );
document.write( '        </div>\n' );
document.write( '    </div>' );
document.write( '    <label class=\"search\">\n' );
document.write( '        <input type=\"text\" class=\"search-input forlargescreen\" onfocus=\"this.value=\'\'\" id=\"searchText\"\n' );
document.write( '            onchange=\"search(this.value)\" />\n' );
document.write( '        <img src=\"imgs/search.png\" class=\"search-img\" id=\"searchIcon\" />\n' );
document.write( '    </label>' );
